<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-0815c480559380816a4d1ea211a47e91.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-748b535e376f14d4692bf2b2e5fd6380.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-0815c480559380816a4d1ea211a47e91.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-dfb324f25d9b1687192fa8be62ac8f9c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-08799928d293638fe9563d5c5a2794e5.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-dfb324f25d9b1687192fa8be62ac8f9c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light"><script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-0815c480559380816a4d1ea211a47e91.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.29">

  <title>Deep Learning · Universidad de Montevideo – Explicando la Mejora de los Transformers sobre las RNNs</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-32f7186d2caa3dc8772e3382bfdf7969.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Explicando la Mejora de los Transformers sobre las RNNs</h1>

<div class="quarto-title-authors">
</div>

</section>
<section class="slide level2">

<blockquote class="blockquote">
<p>Última actualización 07/05/2025</p>
</blockquote>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://colab.research.google.com/github/jeffersonrodriguezc/deep-learning-en-3-semanas/blob/main/semana_2/notebooks/Nb_2c_Traduccion_usando_transformers_keras.ipynb"><img data-src="https://colab.research.google.com/assets/colab-badge.svg" class="figure-img"></a></p>
<figcaption>Open In Colab</figcaption>
</figure>
</div>
<p><strong>Los Transformers: Una Nueva Era en el Procesamiento de Secuencias</strong></p>
<p>Las Redes Neuronales Recurrentes (RNNs) han sido una herramienta fundamental para el procesamiento de datos secuenciales, como el lenguaje natural. Sin embargo, los Transformers, propuestos en el artículo <a href="https://arxiv.org/abs/1706.03762">“Attention is all you need”</a>, han revolucionado este campo, ofreciendo ventajas significativas sobre las RNNs. <strong>Los Transformers son redes neuronales profundas que reemplazan las CNNs y las RNNs. Estos introducen la auto-atención (self-attention) permite a los Transformers transmitir información fácilmente a través de las secuencias de entrada.</strong></p>
<p><strong>¿Por qué los Transformers son importantes?</strong></p>
<ul>
<li><strong>Paralelización:</strong> A diferencia de las RNNs, los Transformers pueden procesar todos los elementos de una secuencia en paralelo, lo que permite un entrenamiento mucho más rápido en hardware moderno como GPUs y TPUs.</li>
<li><strong>Captura de dependencias temporales de larga duración:</strong> Los Transformers utilizan mecanismos de atención que permiten a cada posición de la secuencia prestar atención a todas las demás posiciones, facilitando el aprendizaje de relaciones entre elementos distantes. Las RNNs tienen dificultades para esto debido a la necesidad de procesar la secuencia paso a paso.</li>
<li><strong>Flexibilidad:</strong> Los Transformers no hacen suposiciones sobre las relaciones temporales o espaciales en los datos, lo que los hace aplicables a una variedad de tareas más allá del lenguaje, como el procesamiento de imágenes o el análisis de juegos.</li>
</ul>
<p>En este notebook, exploraremos en profundidad los componentes clave de los Transformers y compararemos su funcionamiento con el de las RNNs, destacando las razones de su superioridad.</p>
<h3 id="comparativa-rnns-vs-transformers">Comparativa RNNs vs Transformers</h3>
<table>
<tbody><tr>
<th>
<a href="https://www.tensorflow.org/text/tutorials/nmt_with_attention">RNN+Modelo de Atención</a>
</th>
<th>
Transformer de 1 capa
</th>
</tr>
<tr>
<td>
<img width="411" src="https://www.tensorflow.org/images/tutorials/transformer/RNN+attention-words.png">
</td>
<td>
<img width="400" src="https://www.tensorflow.org/images/tutorials/transformer/Transformer-1layer-words.png">
</td>
</tr>
</tbody></table>
<h3 id="codificación-y-decodificación-del-transformer-en-traducción">Codificación y decodificación del Transformer en traducción</h3>
<p><img src="https://www.tensorflow.org/images/tutorials/transformer/apply_the_transformer_to_machine_translation.gif" alt="Funcionamiento transformers"></p>
<p>Funcionamiento de los Transformers en la traducción de texto. Fuente: <a href="https://ai.googleblog.com/2017/08/transformer-novel-neural-network.html">Blog Google AI</a>.</p>
</section>
<section id="esquema-de-trabajo" class="slide level2">
<h2>Esquema de trabajo</h2>
<p>Con lo anterior en mente, y una vez visto un poco las diferencias entre RNNs y Transformers, vamos a abordar los siguientes contenidos de manera detallada:</p>
<ol type="1">
<li>Prepararás los datos.</li>
<li>Implementarás los componentes necesarios:
<ul>
<li>Embeddings posicionales.</li>
<li>Capas de atención.</li>
<li>El codificador y el decodificador.</li>
</ul></li>
<li>Construirás y entrenarás el Transformer.</li>
<li>Generarás traducciones.</li>
<li>Exportarás el modelo.</li>
</ol>
<h3 id="carga-y-preprocesamiento-de-datos">Carga y Preprocesamiento de Datos</h3>
<p>Cargaremos un conjunto de datos de traducción Portugués-Inglés y utilizaremos un tokenizador para preparar el texto para el modelo. Este conjunto de datos contiene aproximadamente 52.000 ejemplos de entrenamiento, 1.200 de validación y 1.800 de prueba.</p>
<div id="cell-11" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="c1f6baff-7041-48bf-addc-d7fa4da95c2e" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>-&gt; Ejemplos en portugués:
e quando melhoramos a procura , tiramos a única vantagem da impressão , que é a serendipidade .
mas e se estes fatores fossem ativos ?
mas eles não tinham a curiosidade de me testar .

-&gt; Traducción al inglés:
and when you improve searchability , you actually take away the one advantage of print , which is serendipity .
but what if it were active ?
but they did n't test for curiosity .</code></pre>
</div>
</div>
<h4 id="tokenizadores">Tokenizadores</h4>
<p>En nuestro ejemplo vamos a usar los tokenizadores construidos en el tutorial <a href="https://www.tensorflow.org/text/guide/subwords_tokenizer">subword tokenizer</a>. Ese tutorial optimiza dos objetos <code>text.BertTokenizer</code> (uno para inglés, otro para portugués) para <strong>este conjunto de datos</strong> y los exporta en formato <code>saved_model</code> de TensorFlow.</p>
<div id="cell-13" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;,&quot;height&quot;:36}}" data-outputid="91b9a5b2-c0e5-445b-bbac-51a9c23c646b" data-execution_count="5">
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>'./ted_hrlr_translate_pt_en_converter_extracted'</code></pre>
</div>
</div>
<div id="cell-15" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="0b6b462f-9167-458e-c681-e7ec4e21597a" data-execution_count="7">
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>['detokenize',
 'get_reserved_tokens',
 'get_vocab_path',
 'get_vocab_size',
 'lookup',
 'tokenize',
 'tokenizer',
 'vocab']</code></pre>
</div>
</div>
<div id="cell-16" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="f4fb09f0-830a-4b0d-f7eb-6ca5834fc9ce" data-execution_count="8">
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>(TensorShape([7010]), TensorShape([7765]))</code></pre>
</div>
</div>
<p>El método <code>tokenize</code> convierte un grupo de oraciones en un grupo de identificadores de tokens de una misma longitud (padding). Este método separa los signos de puntuación, las minúsculas y normaliza el texto de entrada antes de la tokenización. Esta normalización no es visible aquí porque los datos de entrada ya están normalizados.</p>
<div id="cell-18" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="69e8aa12-dcbd-4c08-98bb-7aad21f7f5b7" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>-&gt; Esto es un grupo de cadenas:
and when you improve searchability , you actually take away the one advantage of print , which is serendipity .
but what if it were active ?
but they did n't test for curiosity .</code></pre>
</div>
</div>
<div id="cell-19" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="04184a3f-7407-4df8-91c9-b72ed66e56c2" data-execution_count="10">
<div class="cell-output cell-output-stdout">
<pre><code>-&gt; Este es el grupo de cedena de ID de tokens (con padding)
[2, 72, 117, 79, 1259, 1491, 2362, 13, 79, 150, 184, 311, 71, 103, 2308, 74, 2679, 13, 148, 80, 55, 4840, 1434, 2423, 540, 15, 3]
[2, 87, 90, 107, 76, 129, 1852, 30, 3]
[2, 87, 83, 149, 50, 9, 56, 664, 85, 2512, 15, 3]</code></pre>
</div>
</div>
<p>El método <code>detokenize</code> convierte los ID de token de nuevo en texto legible normal:</p>
<div id="cell-21" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="5719e114-7bf4-471b-f7a7-2f7ac6b3e2e6" data-execution_count="11">
<div class="cell-output cell-output-stdout">
<pre><code>-&gt; Correspondiente texto:
and when you improve searchability , you actually take away the one advantage of print , which is serendipity .
but what if it were active ?
but they did n ' t test for curiosity .</code></pre>
</div>
</div>
<p>El método <code>lookup</code> convierte de token-IDs a token-texto:</p>
<div id="cell-23" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="ea2499bb-b49f-42fe-94c4-d5698023c3a7" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>-&gt; Este es el texto dividido en tokens:</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>&lt;tf.RaggedTensor [[b'[START]', b'and', b'when', b'you', b'improve', b'search', b'##ability',
  b',', b'you', b'actually', b'take', b'away', b'the', b'one', b'advantage',
  b'of', b'print', b',', b'which', b'is', b's', b'##ere', b'##nd', b'##ip',
  b'##ity', b'.', b'[END]']                                                 ,
 [b'[START]', b'but', b'what', b'if', b'it', b'were', b'active', b'?',
  b'[END]']                                                           ,
 [b'[START]', b'but', b'they', b'did', b'n', b"'", b't', b'test', b'for',
  b'curiosity', b'.', b'[END]']                                          ]&gt;</code></pre>
</div>
</div>
<p>La salida demuestra el aspecto de <code>"subword"</code> de la tokenización de subpalabras.</p>
<p>Por ejemplo, la palabra <code>'searchability'</code> se descompone en <code>'search'</code> y <code>'##ability'</code>, y la palabra <code>'serendipity'</code> en <code>'s'</code>, <code>'##ere'</code>, <code>'##nd'</code>, <code>'##ip'</code> e <code>'##ity'</code>.</p>
<p>Ten en cuenta que el texto tokenizado incluye los tokens <code>'[START]'</code> y <code>'[END]'</code>.</p>
<p>La distribución de tokens por ejemplo en el conjunto de datos es la siguiente:</p>
<div id="cell-25" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="7e7a42b6-e2f1-4489-ca09-e1f9de91d2b4" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>...................................................</code></pre>
</div>
</div>
<div id="cell-26" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;,&quot;height&quot;:453}}" data-outputid="938c846b-2729-4a39-fa2d-433a3ac26e68" data-execution_count="14">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img data-src="Nb_2c_Traduccion_usando_transformers_keras_files/figure-revealjs/cell-15-output-1.png" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<h4 id="configuración-del-pipeline-de-datos-usando-tf.data">Configuración del pipeline de datos usando <code>tf.data</code></h4>
<p>La siguiente función toma batches de texto como entrada y los convierte a un formato adecuado para el entrenamiento.</p>
<ol type="1">
<li>Los tokeniza en lotes de diferentes dimensiones (ragged).</li>
<li>Recorta cada uno para que no tenga más de <code>MAX_TOKENS</code>.</li>
<li>Divide los tokens objetivo (inglés) en entradas y etiquetas. Estos se desplazan un paso de modo que en cada ubicación de entrada, la <code>etiqueta</code> es el ID del siguiente token.</li>
<li>Convierte los <code>RaggedTensor</code> en <code>Tensor</code> densos con padding.</li>
<li>Devuelve un par <code>(entradas, etiquetas)</code>.</li>
</ol>
<p>La siguiente función convierte un conjunto de datos de ejemplos de texto en datos de lotes para el entrenamiento.</p>
<ol type="1">
<li>Tokeniza el texto y filtra las secuencias que son demasiado largas.</li>
<li>El método <code>cache</code> asegura que ese trabajo solo se ejecute una vez.</li>
<li>Luego, <code>shuffle</code> y preparar el batch.</li>
<li>Finalmente, <code>prefetch</code> ejecuta el conjunto de datos en paralelo con el modelo para asegurar que los datos estén disponibles cuando se necesiten. Consulta <a href="https://www.tensorflow.org/guide/data_performance.ipynb">Mejorar rendimiento con <code>tf.data</code></a> para más detalles.</li>
</ol>
<h4 id="probar-nuestro-pipeline-de-datos">Probar nuestro pipeline de datos</h4>
<p>Como se verían las entradas y sálidas en nuestro pipeline de datos?</p>
<table>
<tbody><tr>
<th>
Inputs en la parte inferior, labels en la parte superior.
</th>
</tr>
<tr>
<td>
<img width="400" src="https://www.tensorflow.org/images/tutorials/transformer/Transformer-1layer-words.png">
</td>
</tr>
</tbody></table>
<p>Esta configuración se llama “<strong>teacher forcing</strong>” porque, independientemente de la salida del modelo en cada paso de tiempo, recibe el valor verdadero como entrada para el siguiente paso de tiempo. Esta es una forma simple y eficiente de entrenar un modelo de generación de texto. Es eficiente porque no necesitas ejecutar el modelo secuencialmente; las salidas en las diferentes ubicaciones de la secuencia se pueden calcular en paralelo.</p>
<div id="cell-38" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="1b645a21-aadf-4167-dec5-b70f7a9ff417" data-execution_count="19">
<div class="cell-output cell-output-stdout">
<pre><code>(64, 64)
(64, 64)
(64, 64)</code></pre>
</div>
</div>
<p>Las etiquetas <code>en</code> y <code>en_labels</code> son las mismas, sólo que desplazadas en 1:</p>
<div id="cell-40" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="da38b3e1-7f43-442e-8c89-e55c8e33477c" data-execution_count="20">
<div class="cell-output cell-output-stdout">
<pre><code>tf.Tensor([ 2 90 80 81 85 30  0  0  0  0], shape=(10,), dtype=int64)
tf.Tensor([90 80 81 85 30  3  0  0  0  0], shape=(10,), dtype=int64)</code></pre>
</div>
</div>
<h3 id="definir-los-componentes-del-transformer">Definir los componentes del Transformer</h3>
<p>Dentro de un Transformer pasan muchas cosas. Las cosas importantes que hay que recordar son:</p>
<ul>
<li>Sigue el mismo patrón general que un modelo estándar secuencia-a-secuencia con un codificador y un decodificador.</li>
<li>Si trabajas paso a paso, todo tendrá sentido.</li>
</ul>
<table>
<tbody><tr>
<th colspan="1">
Diagrama original del Transformer
</th>
<th colspan="1">
Representación de un Transformer de 4 capas
</th>
</tr>
<tr>
<td>
<img width="400" src="https://www.tensorflow.org/images/tutorials/transformer/transformer.png">
</td>
<td>
<img width="307" src="https://www.tensorflow.org/images/tutorials/transformer/Transformer-4layer-compact.png">
</td>
</tr>
</tbody></table>
<h4 id="la-capa-para-la-codificación-de-la-posición">La capa para la codificación de la posición</h4>
<p>Las entradas tanto del codificador como del descodificador utilizan la misma lógica de incrustación y codificación posicional</p>
<table>
<tbody><tr>
<th colspan="1">
The embedding and positional encoding layer
</th>
</tr><tr>
</tr><tr>
<td>
<img src="https://www.tensorflow.org/images/tutorials/transformer/PositionalEmbedding.png">
</td>
</tr>
</tbody></table>
<p>Dada una secuencia de tokens, tanto los tokens de entrada (portugués) como los tokens objetivo (inglés) deben convertirse en vectores utilizando una capa <code>tf.keras.layers.Embedding</code>.</p>
<p>Las capas de atención utilizadas en todo el modelo ven su entrada como un conjunto de vectores, sin ningún orden. Dado que el modelo no contiene ninguna capa recurrente o convolucional, necesita alguna forma de identificar el orden de las palabras; de lo contrario, vería la secuencia de entrada como una instancia de <a href="https://developers.google.com/machine-learning/glossary#bag-of-words">bolsa de palabras</a>, <code>cómo estás</code>, <code>cómo tú estás</code>, <code>tú cómo estás</code>, y así sucesivamente, son indistinguibles.</p>
<p>Por lo tanto, el Transformer agrega una “Codificación Posicional” a los vectores de embedding. Utiliza un conjunto de senos y cosenos en diferentes frecuencias (a lo largo de la secuencia). Por definición, los elementos cercanos tendrán codificaciones posicionales similares.</p>
<p>El paper original usa la siguiente formúla para la codificación posicional:</p>
<p><span class="math display">\[\Large{PE_{(pos, 2i)} = \sin(pos / 10000^{2i / d_{model}})} \]</span> <span class="math display">\[\Large{PE_{(pos, 2i+1)} = \cos(pos / 10000^{2i / d_{model}})} \]</span></p>
<p>Nota: El código a continuación lo implementa, pero en lugar de intercalar los senos y cosenos, los vectores de senos y cosenos simplemente se concatenan. Permutar los canales de esta manera es funcionalmente equivalente, y un poco más fácil de implementar y mostrar en las gráficas siguientes.</p>
<p><strong>Explicación Paso a Paso:</strong> Imaginemos que tenemos una frase: “<strong>El gato está en la alfombra</strong>”.</p>
<p>Y supongamos que d_model = 4. Esto significa que cada posición (cada palabra) se representará con un vector de 4 números.</p>
<ol type="1">
<li>Posiciones:</li>
</ol>
<ul>
<li>“El” está en la posición 0.</li>
<li>“gato” está en la posición 1.</li>
<li>“está” está en la posición 2.</li>
<li>“en” está en la posición 3.</li>
<li>“la” está en la posición 4.</li>
<li>“alfombra” está en la posición 5.</li>
</ul>
<ol start="2" type="1">
<li>Dimensiones:</li>
</ol>
<p>Como d_model = 4, tendremos dimensiones 0, 1, 2, y 3 en nuestro vector de codificación posicional.</p>
<ol start="3" type="1">
<li>Aplicando la Fórmula (Ejemplo: la palabra “gato” en la posición 1):</li>
</ol>
<ul>
<li>Para la dimensión 0 (2i = 0, entonces i = 0):</li>
</ul>
<pre><code>PE(1, 0) = sin(1 / 10000^(2*0 / 4)) = sin(1 / 10000^0) = sin(1 / 1) = sin(1) ≈ 0.841</code></pre>
<ul>
<li>Para la dimensión 1 (2i + 1 = 1, entonces i = 0):</li>
</ul>
<pre><code>PE(1, 1) = cos(1 / 10000^(2*0 / 4)) = cos(1 / 10000^0) = cos(1 / 1) = cos(1) ≈ 0.540</code></pre>
<ul>
<li>Para la dimensión 2 (2i = 2, entonces i = 1):</li>
</ul>
<pre><code>PE(1, 2) = sin(1 / 10000^(2*1 / 4)) = sin(1 / 10000^(1/2)) = sin(1 / 100) = sin(0.01) ≈ 0.01</code></pre>
<ul>
<li>Para la dimensión 3 (2i + 1 = 3, entonces i = 1):</li>
</ul>
<pre><code>PE(1, 3) = cos(1 / 10000^(2*1 / 4)) = cos(1 / 10000^(1/2)) = cos(1 / 100) = cos(0.01) ≈ 0.99995</code></pre>
<p>Entonces, la codificación posicional para la palabra “gato” (posición 1) sería aproximadamente el vector: [0.841, 0.540, 0.01, 0.99995].</p>
<p>La función de codificación de posición es una pila de senos y cosenos que vibran a distintas frecuencias según su ubicación a lo largo de la profundidad del vector de incrustación. Vibran a través del eje de posición.</p>
<div id="cell-51" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="7ddc76d9-1585-4a8c-da6d-0c270edd72e5" data-execution_count="22">
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>&lt;tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[ 0.        ,  0.        ,  1.        ,  1.        ],
       [ 0.84147096,  0.00999983,  0.5403023 ,  0.99995   ],
       [ 0.9092974 ,  0.01999867, -0.41614684,  0.9998    ],
       [ 0.14112   ,  0.0299955 , -0.9899925 ,  0.99955004],
       [-0.7568025 ,  0.03998933, -0.6536436 ,  0.9992001 ],
       [-0.9589243 ,  0.04997917,  0.2836622 ,  0.99875027]],
      dtype=float32)&gt;</code></pre>
</div>
</div>
<div id="cell-52" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;,&quot;height&quot;:472}}" data-outputid="d7a7faee-b156-4fad-af17-41e7cfa76045" data-execution_count="23">
<div class="cell-output cell-output-stdout">
<pre><code>(2048, 512)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img data-src="Nb_2c_Traduccion_usando_transformers_keras_files/figure-revealjs/cell-24-output-2.png" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Por definición, estos vectores se alinean bien con los vectores cercanos a lo largo del eje de posición. A continuación, los vectores de codificación de posición se normalizan y el vector de la posición <code>1000</code> se compara, por producto punto, con todos los demás:</p>
<div id="cell-54" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;,&quot;height&quot;:435}}" data-outputid="5a4e4e72-104c-4070-b4a8-aa3631e08fe9" data-execution_count="24">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img data-src="Nb_2c_Traduccion_usando_transformers_keras_files/figure-revealjs/cell-25-output-1.png" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Ahora creemos la capa: <code>PositionEmbedding</code></p>
<div id="cell-58" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="fc44d343-b3ca-4578-d343-962d14fe2bfb" data-execution_count="27">
<div class="cell-output cell-output-display" data-execution_count="27">
<pre><code>&lt;tf.Tensor: shape=(64, 64), dtype=bool, numpy=
array([[ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       ...,
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False]])&gt;</code></pre>
</div>
</div>
<div id="cell-59" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="c17f885f-f5b1-4542-d187-09b3c71b4712" data-execution_count="28">
<div class="cell-output cell-output-display" data-execution_count="28">
<pre><code>&lt;tf.Tensor: shape=(64, 64, 512), dtype=float32, numpy=
array([[[ 0.81105447, -0.7717942 ,  0.5229695 , ...,  0.02146667,
          0.24027777,  0.26449662],
        [ 1.8670975 ,  1.6279981 ,  0.97901094, ...,  1.3392618 ,
          0.8188071 ,  0.21744752],
        [-0.11729413,  0.5008898 ,  0.32620972, ...,  0.27159345,
          1.1697826 ,  1.4658518 ],
        ...,
        [-1.3773707 ,  0.633837  ,  1.1719698 , ...,  1.6278234 ,
          0.05931401,  0.90110606],
        [-1.1504335 , -0.23321328,  1.8688756 , ...,  1.6278226 ,
          0.0593133 ,  0.90110534],
        [-0.24389721, -0.9982976 ,  1.8318357 , ...,  1.6278219 ,
          0.05931258,  0.9011047 ]],

       [[ 0.81105447, -0.7717942 ,  0.5229695 , ...,  0.02146667,
          0.24027777,  0.26449662],
        [-0.03075731,  0.79514253,  1.7891788 , ...,  0.0534128 ,
          0.01318026,  0.86922586],
        [ 1.0960544 ,  0.75714344,  0.7072108 , ...,  0.3786983 ,
          1.0271425 ,  1.3102653 ],
        ...,
        [-1.3773707 ,  0.633837  ,  1.1719698 , ...,  1.6278234 ,
          0.05931401,  0.90110606],
        [-1.1504335 , -0.23321328,  1.8688756 , ...,  1.6278226 ,
          0.0593133 ,  0.90110534],
        [-0.24389721, -0.9982976 ,  1.8318357 , ...,  1.6278219 ,
          0.05931258,  0.9011047 ]],

       [[ 0.81105447, -0.7717942 ,  0.5229695 , ...,  0.02146667,
          0.24027777,  0.26449662],
        [ 1.7584805 ,  1.4909694 , -0.1760881 , ...,  2.1180818 ,
          0.4953122 ,  0.23008263],
        [ 0.55767405,  1.4934946 ,  0.02770001, ...,  0.84077555,
          0.9217277 ,  1.9566159 ],
        ...,
        [-1.3773707 ,  0.633837  ,  1.1719698 , ...,  1.6278234 ,
          0.05931401,  0.90110606],
        [-1.1504335 , -0.23321328,  1.8688756 , ...,  1.6278226 ,
          0.0593133 ,  0.90110534],
        [-0.24389721, -0.9982976 ,  1.8318357 , ...,  1.6278219 ,
          0.05931258,  0.9011047 ]],

       ...,

       [[ 0.81105447, -0.7717942 ,  0.5229695 , ...,  0.02146667,
          0.24027777,  0.26449662],
        [ 0.7150625 ,  1.6491615 ,  1.213108  , ...,  1.0735046 ,
          0.3283956 ,  0.01745564],
        [ 1.1696244 ,  1.2925339 ,  1.6480486 , ...,  0.24500364,
          1.4749924 ,  1.9941585 ],
        ...,
        [-1.3773707 ,  0.633837  ,  1.1719698 , ...,  1.6278234 ,
          0.05931401,  0.90110606],
        [-1.1504335 , -0.23321328,  1.8688756 , ...,  1.6278226 ,
          0.0593133 ,  0.90110534],
        [-0.24389721, -0.9982976 ,  1.8318357 , ...,  1.6278219 ,
          0.05931258,  0.9011047 ]],

       [[ 0.81105447, -0.7717942 ,  0.5229695 , ...,  0.02146667,
          0.24027777,  0.26449662],
        [-0.23110986,  0.5054298 , -0.25015187, ...,  1.1486163 ,
          1.1958522 ,  1.1460018 ],
        [ 1.4417007 , -0.06407106,  0.7872464 , ...,  0.72261333,
          0.1937148 ,  2.0049632 ],
        ...,
        [-1.3773707 ,  0.633837  ,  1.1719698 , ...,  1.6278234 ,
          0.05931401,  0.90110606],
        [-1.1504335 , -0.23321328,  1.8688756 , ...,  1.6278226 ,
          0.0593133 ,  0.90110534],
        [-0.24389721, -0.9982976 ,  1.8318357 , ...,  1.6278219 ,
          0.05931258,  0.9011047 ]],

       [[ 0.81105447, -0.7717942 ,  0.5229695 , ...,  0.02146667,
          0.24027777,  0.26449662],
        [ 1.7306108 ,  1.4167533 ,  1.2637417 , ..., -0.04352736,
          0.04924804,  0.62587   ],
        [ 0.03706914,  0.90970105,  1.9453614 , ...,  0.0534128 ,
          0.01318026,  0.86922586],
        ...,
        [-1.3773707 ,  0.633837  ,  1.1719698 , ...,  1.6278234 ,
          0.05931401,  0.90110606],
        [-1.1504335 , -0.23321328,  1.8688756 , ...,  1.6278226 ,
          0.0593133 ,  0.90110534],
        [-0.24389721, -0.9982976 ,  1.8318357 , ...,  1.6278219 ,
          0.05931258,  0.9011047 ]]], dtype=float32)&gt;</code></pre>
</div>
</div>
<h4 id="capas-de-adición-y-normalización">Capas de Adición y normalización</h4>
<table>
<tbody><tr>
<th colspan="2">
Add y normalize
</th>
</tr><tr>
</tr><tr>
<td>
<img src="https://www.tensorflow.org/images/tutorials/transformer/Add+Norm.png">
</td>
</tr>
</tbody></table>
<p>Estos bloques de “Add &amp; Norm” se encuentran distribuidos a lo largo de todo el modelo Transformer. Cada uno combina una conexión residual y pasa el resultado a través de una capa de <code>LayerNormalization</code>.</p>
<p>La manera más sencilla de organizar el código es estructurándolo alrededor de estos bloques residuales. En las siguientes secciones, definiremos clases de capas personalizadas para cada uno de ellos.</p>
<p>Los bloques residuales “Add &amp; Norm” se incluyen para que el entrenamiento sea eficiente. La conexión residual proporciona una ruta directa para el gradiente (y asegura que los vectores sean <strong>actualizados</strong> por las capas de atención en lugar de ser <strong>reemplazados</strong>), mientras que la normalización mantiene una escala razonable para las salidas.</p>
<p><strong>Nota</strong>: Las implementaciones que se muestran a continuación utilizan la capa <code>Add</code> para asegurar que las máscaras de Keras se propaguen correctamente (el operador <code>+</code> no lo hace).</p>
<h4 id="bases-de-la-capa-de-atención">Bases de la capa de atención</h4>
<p>Las capas de atención se utilizan a lo largo de todo el modelo Transformer. Todas ellas son idénticas, excepto por cómo se configura la atención. Cada una contiene una capa <code>layers.MultiHeadAttention</code>, una capa <code>layers.LayerNormalization</code> y una capa <code>layers.Add</code>.</p>
<table>
<tbody><tr>
<th colspan="2">
Capa de atención básica
</th>
</tr><tr>
</tr><tr>
<td>
<img src="https://www.tensorflow.org/images/tutorials/transformer/BaseAttention.png">
</td>
</tr>
</tbody></table>
<p>Para implementar estas capas de atención, comenzaremos con una clase base simple que sólo contenga definidos los componentes. Cada caso de uso se implementará como una subclase (framework).</p>
<h5 id="atención-cómo-funciona"><strong>Atención, cómo funciona?</strong></h5>
<p>Antes de entrar en los detalles de cada uso, aquí tienes un breve repaso de cómo funciona la atención:</p>
<table>
<tbody><tr>
<th colspan="1">
Capa de atención básica
</th>
</tr>
<tr>
<td>
<img width="430" src="https://www.tensorflow.org/images/tutorials/transformer/BaseAttention-new.png">
</td>
</tr>
</tbody></table>
<p>Hay dos entradas: 1. La secuencia de consulta (<em>query sequence</em>): la secuencia que se está procesando; la secuencia que “atiende” (abajo). 2. La secuencia de contexto (<em>context sequence</em>): la secuencia a la que se está “atendiendo” (izquierda).</p>
<p>La salida tiene la misma forma que la secuencia de consulta.</p>
<p>Una analogía común es que esta operación se asemeja a una búsqueda en un diccionario. Una búsqueda en un diccionario <strong>difuso</strong>, <strong>diferenciable</strong> y <strong>vectorizado</strong>.</p>
<p>Aquí tienes un diccionario regular de Python, con 3 claves y 3 valores al que se le pasa una única consulta.</p>
<pre><code>d = {'color': 'azul', 'edad': 22, 'tipo': 'pickup'}
result = d['color']</code></pre>
<ul>
<li>El <code>query</code> es lo que se esta tratando de encontrar.</li>
<li>The <code>key</code> es el tipo de información que tiene el diccionario</li>
<li>The <code>value</code> es la información</li>
</ul>
<p>Cuando buscas una <code>query</code> (consulta) en un diccionario normal, el diccionario encuentra la <code>key</code> (clave) coincidente y devuelve su <code>value</code> (valor) asociado. La <code>query</code> tiene una <code>key</code> coincidente o no la tiene.</p>
<p>Puedes imaginar un diccionario <strong>difuso</strong> donde las claves no tienen que coincidir perfectamente. Si buscaras <code>d["especie"]</code> en el diccionario de arriba, quizás querrías que devolviera <code>"pickup"</code> ya que es la mejor coincidencia para la consulta.</p>
<p>Una capa de atención realiza una búsqueda difusa como esta, pero no solo busca la mejor clave. Combina los <code>values</code> basándose en qué tan bien la <code>query</code> coincide con cada <code>key</code>.</p>
<p>¿Cómo funciona esto? En una capa de atención, la <code>query</code>, la <code>key</code> y el <code>value</code> son cada uno vectores. En lugar de realizar una búsqueda de asignación, la capa de atención combina los vectores de la <code>query</code> y la <code>key</code> para determinar qué tan bien coinciden, obteniendo una “puntuación de atención” (<em>attention score</em>). La capa devuelve el promedio de todos los <code>values</code>, ponderado por las “puntuaciones de atención”.</p>
<p>Cada posición en la secuencia de consulta (<em>query sequence</em>) proporciona un vector de <code>query</code>. La secuencia de contexto (<em>context sequence</em>) actúa como el diccionario. Cada posición en la secuencia de contexto proporciona un vector de <code>key</code> y un vector de <code>value</code>.</p>
<p>Los vectores de entrada no se utilizan directamente; la capa <code>layers.MultiHeadAttention</code> incluye capas <code>layers.Dense</code> para proyectar los vectores de entrada antes de utilizarlos.</p>
<h5 id="capa-de-atención-cruzada"><strong>Capa de atención cruzada</strong></h5>
<p>En el centro literal del Transformer está la capa de atención cruzada. Esta capa conecta el codificador y el decodificador. Esta capa es el uso más directo de la atención en el modelo, realiza la misma tarea que el bloque de atención en el <a href="https://www.tensorflow.org/text/tutorials/nmt_with_attention">Tutorial NMT con atención</a>.</p>
<table>
<tbody><tr>
<th colspan="1">
Atención cruzada
</th>
</tr><tr>
</tr><tr>
<td>
<img src="https://www.tensorflow.org/images/tutorials/transformer/CrossAttention.png">
</td>
</tr>
</tbody></table>
<p>Para implementar esto, pasas la secuencia objetivo <code>x</code> como la <code>query</code> (consulta) y la secuencia de <code>context</code> (contexto) como la <code>key/value</code> (clave/valor) al llamar a la capa <code>mha</code>:</p>
<p>La siguiente caricatura muestra cómo fluye la información a través de esta capa. Las columnas representan la suma ponderada de la secuencia contextual.</p>
<p>Para simplificar, no se muestran las conexiones residuales.</p>
<table>
<tbody><tr>
<th>
Atención cruzada
</th>
</tr>
<tr>
<td>
<img width="430" src="https://www.tensorflow.org/images/tutorials/transformer/CrossAttention-new-full.png">
</td>
</tr>
</tbody></table>
<p>La longitud de la salida es la longitud de la secuencia de <code>query</code> (consulta), y no la longitud de la secuencia de <code>key/value</code> (clave/valor) del contexto.</p>
<p>El diagrama se simplifica aún más a continuación. No es necesario dibujar la matriz completa de “pesos de atención”.</p>
<p>El punto clave es que cada ubicación en la <code>query</code> puede “ver” todos los pares de <code>key/value</code> en el contexto, pero no se intercambia información entre las diferentes consultas.</p>
<table>
<tbody><tr>
<th>
Cada elemento del query puede ver todo el contexto.
</th>
</tr>
<tr>
<td>
<img width="430" src="https://www.tensorflow.org/images/tutorials/transformer/CrossAttention-new.png">
</td>
</tr>
</tbody></table>
<p>Ejemplo:</p>
<div id="cell-78" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="5e1de892-1052-40fa-e9f9-f73e7b2297dd" data-execution_count="31">
<div class="cell-output cell-output-stdout">
<pre><code>(64, 64, 512)
(64, 64, 512)
(64, 64, 512)</code></pre>
</div>
</div>
<h5 id="capa-global-de-auto-atención"><strong>Capa global de auto-atención</strong></h5>
<p>Esta capa se encarga de procesar la secuencia contextual y de propagar la información a lo largo de la misma:</p>
<table>
<tbody><tr>
<th colspan="1">
La capa global de auto-atención
</th>
</tr><tr>
</tr><tr>
<td>
<img src="https://www.tensorflow.org/images/tutorials/transformer/SelfAttention.png">
</td>
</tr>
</tbody></table>
<p>Dado que la secuencia contextual es fija mientras se genera la traducción (entrenamiento), se permite que la información fluya en ambas direcciones.</p>
<p>Antes de los Transformers y la autoatención, los modelos solían utilizar RNNs o CNNs para realizar esta tarea (bidireccionalidad):</p>
<table>
<tbody><tr>
<th colspan="1">
RNNs y CNNs bidireccionales
</th>
</tr>
<tr>
<td>
<img width="500" src="https://www.tensorflow.org/images/tutorials/transformer/RNN-bidirectional.png">
</td>
</tr>
<tr>
<td>
<img width="500" src="https://www.tensorflow.org/images/tutorials/transformer/CNN.png">
</td>
</tr>
</tbody></table>
<p>RNNs and CNNs have their limitations.</p>
<p>Las RNNs y las CNNs tienen sus limitaciones:</p>
<ul>
<li>La RNN permite que la información fluya a lo largo de toda la secuencia, pero atraviesa muchos pasos de procesamiento para llegar allí (limitando el flujo del gradiente). Estos pasos de la RNN deben ejecutarse secuencialmente, por lo que la RNN es menos capaz de aprovechar los dispositivos paralelos modernos.</li>
<li>En la CNN, cada ubicación puede procesarse en paralelo, pero solo proporciona un campo receptivo limitado. El campo receptivo solo crece linealmente con el número de capas CNN. Se necesita apilar varias capas convolucionales para transmitir información a través de la secuencia.</li>
</ul>
<p>Por otro lado, la capa de auto-atención global permite que cada elemento de la secuencia acceda directamente a todos los demás elementos de la secuencia, con solo unas pocas operaciones, y todas las salidas se pueden calcular en paralelo.</p>
<p>Para implementar esta capa, solo necesitas pasar la secuencia objetivo, <code>x</code>, como los argumentos <code>query</code> (consulta) y <code>value</code> (valor) a la capa <code>mha</code>:</p>
<div id="cell-86" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="2ce9565e-ab51-4667-a5ed-7ac88d6c1355" data-execution_count="33">
<div class="cell-output cell-output-stdout">
<pre><code>(64, 64, 512)
(64, 64, 512)</code></pre>
</div>
</div>
<p>Siguiendo con el mismo estilo de antes, podriamos dibujarlo así:</p>
<table>
<tbody><tr>
<th colspan="1">
La capa global de auto-atención
</th>
</tr><tr>
</tr><tr>
<td>
<img width="330" src="https://www.tensorflow.org/images/tutorials/transformer/SelfAttention-new-full.png">
</td>
</tr>
</tbody></table>
<p>De nuevo, las conexiones residuales se omiten para mayor claridad.</p>
<p>Es más compacto e igual de preciso dibujarlo así:</p>
<table>
<tbody><tr>
<th colspan="1">
La capa de auto-atención global
</th>
</tr><tr>
</tr><tr>
<td>
<img width="500" src="https://www.tensorflow.org/images/tutorials/transformer/SelfAttention-new.png">
</td>
</tr>
</tbody></table>
<h5 id="capa-de-auto-atención-causal"><strong>Capa de auto-atención causal</strong></h5>
<p>Esta capa realiza un trabajo similar al de la capa de autoatención global, para la secuencia de salida:</p>
<table>
<tbody><tr>
<th colspan="1">
Capa causal de auto-atención
</th>
</tr><tr>
</tr><tr>
<td>
<img src="https://www.tensorflow.org/images/tutorials/transformer/CausalSelfAttention.png">
</td>
</tr>
</tbody></table>
<p>This needs to be handled differently from the encoder’s global self-attention layer.</p>
<p>Like the <a href="https://www.tensorflow.org/text/tutorials/text_generation">text generation tutorial</a>, and the <a href="https://www.tensorflow.org/text/tutorials/nmt_with_attention">NMT with attention</a> tutorial, Transformers are an “autoregressive” model: They generate the text one token at a time and feed that output back to the input. To make this <em>efficient</em>, these models ensure that the output for each sequence element only depends on the previous sequence elements; the models are “causal”.</p>
<p>Una RNN unidireccional es causal por definición. Para hacer una convolución causal, solo necesitas rellenar (<em>pad</em>) la entrada y desplazar la salida para que se alinee correctamente (puedes usar <code>layers.Conv1D(padding='causal')</code>).</p>
<table>
<tbody><tr>
<th colspan="1">
Causalidad en RNNs y CNNs
</th>
</tr>
<tr>
<td>
<img width="500" src="https://www.tensorflow.org/images/tutorials/transformer/RNN.png">
</td>
</tr>
<tr>
<td>
<img width="500" src="https://www.tensorflow.org/images/tutorials/transformer/CNN-causal.png">
</td>
</tr>
</tbody></table>
<p>Un modelo causal es eficiente de dos maneras:</p>
<ol type="1">
<li><strong>En el entrenamiento</strong>, te permite calcular la pérdida para cada posición en la secuencia de salida ejecutando el modelo una sola vez.</li>
<li><strong>Durante la inferencia</strong>, para cada nuevo token generado, solo necesitas calcular sus salidas; las salidas de los elementos de la secuencia anterior se pueden reutilizar.
<ul>
<li>Para una RNN, solo necesitas el estado de la RNN para tener en cuenta los cálculos previos (pasa <code>return_state=True</code> al constructor de la capa RNN).</li>
<li>Para una CNN, necesitarías seguir el enfoque de <a href="https://arxiv.org/abs/1611.09482">Fast Wavenet</a>.</li>
</ul></li>
</ol>
<p>Para construir una capa de auto-atención causal, necesitas usar una máscara apropiada al calcular las puntuaciones de atención y sumar los <code>value</code>s de atención.</p>
<p>Esto se gestiona automáticamente si pasas <code>use_causal_mask = True</code> a la capa <code>MultiHeadAttention</code> cuando la llamas:</p>
<p>La máscara causal garantiza que cada lugar sólo tenga acceso a los lugares que le preceden:</p>
<table>
<tbody><tr>
<th colspan="1">
Capa de auto-atención causal.
</th>
</tr><tr>
</tr><tr>
<td>
<img width="330" src="https://www.tensorflow.org/images/tutorials/transformer/CausalSelfAttention-new-full.png">
</td>
</tr>
</tbody></table>
<p>De nuevo, las conexiones residuales se omiten por simplicidad.</p>
<p>La representación más compacta de esta capa sería:</p>
<table>

<tbody><tr><th colspan="1">
Capa de auto-atención causal.
</th>
</tr><tr>
</tr><tr>
<td>
<img width="430" src="https://www.tensorflow.org/images/tutorials/transformer/CausalSelfAttention-new.png">
</td>
</tr>
</tbody></table>
<p>Ejemplo:</p>
<div id="cell-105" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="0c89c6fd-d248-4c33-fd2f-dba9901da126" data-execution_count="35">
<div class="cell-output cell-output-stdout">
<pre><code>(64, 64, 512)
(64, 64, 512)</code></pre>
</div>
</div>
<p>La salida de los primeros elementos de la secuencia no depende de los elementos posteriores, por lo que no debería importar si recorta los elementos antes o después de aplicar la capa:</p>
<div id="cell-107" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="9cdcfa7c-3fc5-472d-b36a-1c6faa882ea0" data-execution_count="36">
<div class="cell-output cell-output-display" data-execution_count="36">
<pre><code>np.float32(7.1525574e-07)</code></pre>
</div>
</div>
<p>Nota: Cuando se utilizan máscaras Keras, los valores de salida en lugares no válidos no están bien definidos. Por lo tanto, lo anterior puede no ser válido para las regiones enmascaradas.</p>
<h4 id="la-red-feed-forward-mlp">La red feed forward (MLP)</h4>
<p>El Transformer también incluye esta red neuronal feed-forward <em>point-wise</em> tanto en el codificador como en el decodificador:</p>
<table>
<tbody><tr>
<th colspan="1">
La red feed forward (MLP)
</th>
</tr><tr>
</tr><tr>
<td>
<img src="https://www.tensorflow.org/images/tutorials/transformer/FeedForward.png">
</td>
</tr>
</tbody></table>
<p>La red consiste en dos capas lineales (<code>tf.keras.layers.Dense</code>) con una función de activación ReLU entre ellas, y una capa de dropout. Al igual que con las capas de atención, el código aquí también incluye la conexión residual y la normalización:</p>
<p>Prueba:</p>
<div id="cell-115" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="f55e79ff-ff9a-4080-ee10-723c7b648947" data-execution_count="38">
<div class="cell-output cell-output-stdout">
<pre><code>(64, 64, 512)
(64, 64, 512)</code></pre>
</div>
</div>
<h4 id="la-capa-encoder">La capa encoder</h4>
<p>El codificador contiene una pila de <code>N</code> capas de codificador. Donde cada <code>EncoderLayer</code> contiene una capa <code>GlobalSelfAttention</code> y una capa <code>FeedForward</code>:</p>
<table>
<tbody><tr>
<th colspan="1">
La capa encoder
</th>
</tr><tr>
</tr><tr>
<td>
<img src="https://www.tensorflow.org/images/tutorials/transformer/EncoderLayer.png">
</td>
</tr>
</tbody></table>
<p>Aquí la estructura de la capa <code>EncoderLayer</code>:</p>
<p>Prueba:</p>
<div id="cell-122" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="63875d50-ad27-4ece-c02b-8d16d1715934" data-execution_count="40">
<div class="cell-output cell-output-stdout">
<pre><code>(64, 64, 512)
(64, 64, 512)</code></pre>
</div>
</div>
<h4 id="el-módulo-encoder">El módulo Encoder</h4>
<p>Construyamos el encoder, agregandole la parte de embedings y la codificación posicional.</p>
<table>
<tbody><tr>
<th colspan="1">
El encoder
</th>
</tr><tr>
</tr><tr>
<td>
<img src="https://www.tensorflow.org/images/tutorials/transformer/Encoder.png">
</td>
</tr>
</tbody></table>
<p>El codificador consiste en:</p>
<ul>
<li>Una capa <code>PositionalEmbedding</code> en la entrada.</li>
<li>Una pila de capas <code>EncoderLayer</code>.</li>
</ul>
<p>Probar:</p>
<div id="cell-129" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="ce94a408-5480-41d9-83de-9a4f621549c7" data-execution_count="42">
<div class="cell-output cell-output-stdout">
<pre><code>(64, 64)
(64, 64, 512)</code></pre>
</div>
</div>
<h4 id="la-capa-decoder">La capa decoder</h4>
<p>El decodificador es ligeramente más compleja, con cada <code>DecoderLayer</code> conteniendo una capa <code>CausalSelfAttention</code>, una capa <code>CrossAttention</code> y una capa <code>FeedForward</code>:</p>
<table>
<tbody><tr>
<th colspan="1">
La capa decoder
</th>
</tr><tr>
</tr><tr>
<td>
<img src="https://www.tensorflow.org/images/tutorials/transformer/DecoderLayer.png">
</td>
</tr>
</tbody></table>
<p>Probar la capa del decoder:</p>
<div id="cell-135" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="4e920438-e86e-4907-b88a-647fa49cc35c" data-execution_count="44">
<div class="cell-output cell-output-stdout">
<pre><code>(64, 64, 512)
(64, 64, 512)
(64, 64, 512)</code></pre>
</div>
</div>
<h4 id="el-módulo-decoder">El módulo decoder</h4>
<p>De forma similar al Codificador, el Decodificador consiste en un <code>PositionalEmbedding</code> y una pila de <code>DecoderLayer</code>’s:</p>
<table>
<tbody><tr>
<th colspan="1">
Capa Decoder + Embedding + PE
</th>
</tr><tr>
</tr><tr>
<td>
<img src="https://www.tensorflow.org/images/tutorials/transformer/Decoder.png">
</td>
</tr>
</tbody></table>
<p>Definimos el Decoder extendiendo <code>tf.keras.layers.Layer</code>:</p>
<p>Probar:</p>
<div id="cell-142" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="9b4c661c-4deb-4fd3-df00-3bdb4c3b7b09" data-execution_count="46">
<div class="cell-output cell-output-stdout">
<pre><code>(64, 64)
(64, 64, 512)
(64, 64, 512)</code></pre>
</div>
</div>
<div id="cell-143" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="c689c537-f5e3-4791-e9fd-55bd9d1b2cbb" data-execution_count="47">
<div class="cell-output cell-output-display" data-execution_count="47">
<pre><code>TensorShape([64, 8, 64, 64])</code></pre>
</div>
</div>
<p>Una vez creados el codificador y el decodificador Transformer, es hora de construir el modelo Transformer y entrenarlo.</p>
</section>
<section id="el-transformer" class="slide level2">
<h2>El Transformer</h2>
<p>You now have <code>Encoder</code> and <code>Decoder</code>. To complete the <code>Transformer</code> model, you need to put them together and add a final linear (<code>Dense</code>) layer which converts the resulting vector at each location into output token probabilities.</p>
<p>The output of the decoder is the input to this final linear layer.</p>
<table>
<tbody><tr>
<th colspan="1">
El transformer
</th>
</tr><tr>
</tr><tr>
<td>
<img src="https://www.tensorflow.org/images/tutorials/transformer/transformer.png">
</td>
</tr>
</tbody></table>
<p>Un <code>Transformer</code> con una capa tanto en el <code>Codificador</code> como en el <code>Decodificador</code> se parece casi exactamente al modelo del <a href="https://www.tensorflow.org/text/tutorials/nmt_with_attention">tutorial de RNN+atención</a>. Un Transformer multi-capa tiene más capas, pero fundamentalmente está haciendo lo mismo.</p>
<table>
<tbody><tr>
<th colspan="1">
Transformer de una capa
</th>
<th colspan="1">
Transformer de 4 capas
</th>
</tr>
<tr>
<td>
<img width="400" src="https://www.tensorflow.org/images/tutorials/transformer/Transformer-1layer-compact.png">
</td>
<td rowspan="3">
<img width="330" src="https://www.tensorflow.org/images/tutorials/transformer/Transformer-4layer-compact.png">
</td>
</tr>
<tr>
<th colspan="1">
RNN + Modelo de atención
</th>
</tr>
<tr>
<td>
<img width="400" src="https://www.tensorflow.org/images/tutorials/transformer/RNN+attention-compact.png">
</td>
</tr>
</tbody></table>
<p>Crea el <code>Transformer</code> extendiendo <code>tf.keras.Model</code>:</p>
<blockquote class="blockquote">
<p>Nota: El <a href="https://arxiv.org/pdf/1706.03762.pdf">artículo original</a>, sección 3.4, comparte la matriz de pesos entre la capa de embedding y la capa lineal final. Para mantener las cosas simples, este tutorial utiliza dos matrices de pesos separadas.</p>
</blockquote>
<h3 id="hiperparámetros">Hiperparámetros</h3>
<p>Para mantener este ejemplo pequeño y relativamente rápido, el número de capas (<code>num_layers</code>), la dimensionalidad de los embeddings (<code>d_model</code>) y la dimensionalidad interna de la capa <code>FeedForward</code> (<code>dff</code>) se han reducido.</p>
<p>El modelo base descrito en el artículo original del Transformer utilizaba <code>num_layers=6</code>, <code>d_model=512</code> y <code>dff=2048</code>.</p>
<p>El número de cabezas de auto-atención será (<code>num_heads=4</code>).</p>
<h3 id="probemos-el-transformer">Probemos el transformer</h3>
<p>Instanciar el modelo <code>Transformer</code>:</p>
<p>Probar</p>
<div id="cell-159" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="02c682e4-ca37-4de3-9f08-4d265b8c87a6" data-execution_count="51">
<div class="cell-output cell-output-stdout">
<pre><code>(64, 64)
(64, 64)
(64, 64, 7010)</code></pre>
</div>
</div>
<div id="cell-160" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="886a54f2-7c21-4b88-a1ca-828df2816f21" data-execution_count="52">
<div class="cell-output cell-output-stdout">
<pre><code>(64, 4, 64, 64)</code></pre>
</div>
</div>
</section>
<section id="training" class="slide level2">
<h2>Training</h2>
<p>Tiempo de entrenar!!</p>
<h3 id="configurar-el-optimizador">Configurar el optimizador</h3>
<p>Utilizar el optimizador Adam con un planificador personalizado para la tasa de aprendizaje según la fórmula del Transformer original. <a href="https://arxiv.org/abs/1706.03762">paper</a>.</p>
<p><span class="math display">\[\Large{lrate = d_{model}^{-0.5} * \min(step{\_}num^{-0.5}, step{\_}num \cdot warmup{\_}steps^{-1.5})}\]</span></p>
<h3 id="explicación-esquema-de-learning-rate-del-transformer">Explicación esquema de Learning Rate del Transformer</h3>
<p><strong>Parámetros:</strong></p>
<ol type="1">
<li><strong><code>d_model</code> (Dimensionalidad del Modelo):</strong>
<ul>
<li><strong>Intuición:</strong> “Ancho” del modelo. Mayor <code>d_model</code> = representaciones más ricas, más capacidad.</li>
<li><strong>Efecto:</strong> Actúa como un factor de escala base para el learning rate.
<ul>
<li>Si d_model es grande, este factor será pequeño, lo que tiende a reducir el learning rate general. La intuición es que modelos más grandes pueden necesitar pasos de aprendizaje más pequeños para evitar inestabilidad debido a su mayor número de parámetros.</li>
<li>Si d_model es pequeño, este factor será más grande, lo que tiende a aumentar el learning rate general.</li>
</ul></li>
</ul></li>
<li><strong><code>step_num</code> (Número de Paso de Entrenamiento):</strong>
<ul>
<li><strong>Intuición:</strong> Progreso del entrenamiento (iteración actual).</li>
<li><strong>Efecto:</strong> Determina la fase del learning rate:
<ul>
<li><strong>Fase de Decaimiento (<span class="math inline">\({step\\_num}^{-0.5}\)</span>):</strong> Este término hace que el learning rate disminuya a medida que avanza el entrenamiento. La intuición es que al principio queremos dar pasos de aprendizaje más grandes para explorar el espacio de parámetros rápidamente. A medida que nos acercamos a un buen conjunto de pesos, queremos dar pasos más pequeños para “afinar” los valores y evitar oscilar alrededor del mínimo óptimo. La disminución es más pronunciada al principio y se ralentiza con el tiempo.</li>
<li><strong>Fase de Calentamiento (<span class="math inline">\({step\\_num * warmup\\_steps}^{-1.5}\)</span>):</strong> Este término está activo principalmente durante la fase de “calentamiento”. Hace que el learning rate aumente linealmente con el número de paso hasta que step_num se acerca a warmup_steps.</li>
</ul></li>
</ul></li>
<li><strong><code>warmup_steps</code> (Pasos de Calentamiento):</strong>
<ul>
<li><strong>Intuición:</strong> Duración de la fase inicial de aumento gradual del learning rate.</li>
<li><strong>Efecto:</strong> Controla cuántos pasos se tarda en alcanzar el learning rate “base”. Ayuda a evitar inestabilidad al inicio.</li>
</ul></li>
</ol>
<p><strong>En resumen:</strong></p>
<p>El learning rate:</p>
<ul>
<li><strong>Aumenta gradualmente</strong> durante los primeros <code>warmup_steps</code> para estabilizar el entrenamiento inicial.</li>
<li><strong>Disminuye gradualmente</strong> después de <code>warmup_steps</code> para permitir una convergencia fina.</li>
<li>Su magnitud general está influenciada por la dimensionalidad del modelo (<code>d_model</code>).</li>
</ul>
<p>Instanciar el optimizador (<code>tf.keras.optimizers.Adam</code>):</p>
<p>Probar el scheduler para el learning rate:</p>

<img data-src="Nb_2c_Traduccion_usando_transformers_keras_files/figure-revealjs/cell-56-output-1.png" class="r-stretch"><h3 id="ajustar-función-de-pérdida-y-métricas">Ajustar función de pérdida y métricas</h3>
<p>Dado que las secuencias objetivo están rellenadas (padded), es importante aplicar una máscara de padding al calcular la pérdida. Utiliza la función de pérdida de entropía cruzada (<code>tf.keras.losses.SparseCategoricalCrossentropy</code>):</p>
<h3 id="entrenar-el-modelo">Entrenar el modelo</h3>
<p>Con todo listo, vamos a compilar usando <code>model.compile</code>, y luego entrenar con <code>model.fit</code>:</p>
<div id="cell-176" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="44e94123-1951-4247-eb7e-56ae8645f25e" data-execution_count="58">
<div class="cell-output cell-output-stdout">
<div class="ansi-escaped-output">
<pre>Epoch 1/3

<span class="ansi-bold">810/810</span> <span class="ansi-green-fg">━━━━━━━━━━━━━━━━━━━━</span> <span class="ansi-bold">1037s</span> 1s/step - loss: 7.7200 - masked_accuracy: 0.0833 - val_loss: 4.9830 - val_masked_accuracy: 0.2540

Epoch 2/3

<span class="ansi-bold">810/810</span> <span class="ansi-green-fg">━━━━━━━━━━━━━━━━━━━━</span> <span class="ansi-bold">531s</span> 633ms/step - loss: 4.6781 - masked_accuracy: 0.2912 - val_loss: 3.9608 - val_masked_accuracy: 0.3668

Epoch 3/3

<span class="ansi-bold">810/810</span> <span class="ansi-green-fg">━━━━━━━━━━━━━━━━━━━━</span> <span class="ansi-bold">424s</span> 463ms/step - loss: 3.6996 - masked_accuracy: 0.4002 - val_loss: 3.4028 - val_masked_accuracy: 0.4305
</pre>
</div>
</div>
<div class="cell-output cell-output-display" data-execution_count="58">
<pre><code>&lt;keras.src.callbacks.history.History at 0x7bffd0607690&gt;</code></pre>
</div>
</div>
</section>
<section id="ejecutar-inferencia" class="slide level2">
<h2>Ejecutar inferencia</h2>
<p>Ahora puedes probar el modelo realizando una traducción. Los siguientes pasos se utilizan para la inferencia:</p>
<ul>
<li>Codifica la frase de entrada utilizando el tokenizador portugués (<code>tokenizers.pt</code>). Esta es la entrada del codificador.</li>
<li>La entrada del decodificador se inicializa con el token <code>[START]</code>.</li>
<li>Calcula las máscaras de padding y las máscaras causales (para la auto-atención causal).</li>
<li>El <code>decodificador</code> luego genera las predicciones observando la <code>salida del codificador</code> y su propia salida (auto-atención).</li>
<li>Concatena el token predicho a la entrada del decodificador y lo pasa de nuevo al decodificador.</li>
<li>En este enfoque, el decodificador predice el siguiente token basándose en los tokens que predijo previamente.</li>
</ul>
<p>Nota: El modelo está optimizado para un <em>entrenamiento eficiente</em> y realiza una predicción del siguiente token para cada token en la salida simultáneamente. Esto es redundante durante la inferencia, y solo se utiliza la última predicción. Este modelo puede hacerse más eficiente para la inferencia si solo se calcula la última predicción cuando se ejecuta en modo de inferencia (<code>training=False</code>).</p>
<p>Define la clase <code>Translator</code> extendiendo <code>tf.Module</code>:</p>
<p>Nota: Esta función utiliza un bucle unrolled, no un bucle dinámico. Genera <code>MAX_TOKENS</code> en cada llamada. Consulta el tutorial de <a href="https://www.tensorflow.org/text/tutorials/nmt_with_attention">NMT con atención</a> para ver un ejemplo de implementación con un bucle dinámico, que puede ser mucho más eficiente.</p>
<p>Probemos la traducción:</p>
<p>Ejemplo 1:</p>
<div id="cell-184" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="f7461c50-e550-42ff-cf52-6d22000f6861" data-execution_count="61">
<div class="cell-output cell-output-stdout">
<pre><code>Input:         : este é um problema que temos que resolver.
Predicción     : this is a problem that we have to solve .
Ground truth   : this is a problem we have to solve .</code></pre>
</div>
</div>
<p>Ejemplo 2:</p>
<div id="cell-186" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="c9745211-ca89-435f-80ba-f302473539fc" data-execution_count="62">
<div class="cell-output cell-output-stdout">
<pre><code>Input:         : os meus vizinhos ouviram sobre esta ideia.
Predicción     : my friends heard about this idea .
Ground truth   : and my neighboring homes heard about this idea .</code></pre>
</div>
</div>
<p>Ejemplo 3:</p>
<div id="cell-188" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="bc4d00a5-8924-4b5f-f6cf-cde1fa92ecd9" data-execution_count="63">
<div class="cell-output cell-output-stdout">
<pre><code>Input:         : vou então muito rapidamente partilhar convosco algumas histórias de algumas coisas mágicas que aconteceram.
Predicción     : i ' m going very quickly quickly quickly to share with some stories of things , things that will be going to be going to be going to be going to be going to be going to be able to be able to be able to be very good .
Ground truth   : so i'll just share with you some stories very quickly of some magical things that have happened.</code></pre>
</div>
</div>
</section>
<section id="crear-los-plots-de-atención" class="slide level2">
<h2>Crear los plots de atención</h2>
<p>Usando la clase traductor <code>Translator</code> que almacena los scores de atención, podemos usarlos para ver su relevancia:</p>
<p>Por ejemplo:</p>
<div id="cell-191" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="f06ebf36-7546-49e7-ed6a-985ce946bcf4" data-execution_count="64">
<div class="cell-output cell-output-stdout">
<pre><code>Input:         : este é o primeiro livro que eu fiz.
Predicción     : this is the first book that i did i did .
Ground truth   : this is the first book i've ever done.</code></pre>
</div>
</div>
<p>Crear una función que grafique la atención cuando se genera un token:</p>
<div id="cell-193" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="d49ed566-cec1-4fcc-d5b4-57ee29ab6319" data-execution_count="65">
<div class="cell-output cell-output-display" data-execution_count="65">
<pre><code>TensorShape([12, 11])</code></pre>
</div>
</div>
<p>Son las inputs tokens en portugués:</p>
<div id="cell-195" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="da56e799-d926-4749-a04f-592cad4a3661" data-execution_count="66">
<div class="cell-output cell-output-display" data-execution_count="66">
<pre><code>&lt;tf.Tensor: shape=(11,), dtype=string, numpy=
array([b'[START]', b'este', b'e', b'o', b'primeiro', b'livro', b'que',
       b'eu', b'fiz', b'.', b'[END]'], dtype=object)&gt;</code></pre>
</div>
</div>
<p>Estas son las sálidas (tokens en inglés, traducción)</p>
<div id="cell-197" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="aaaef1e6-7d46-4301-9c94-490692ae5336" data-execution_count="67">
<div class="cell-output cell-output-display" data-execution_count="67">
<pre><code>&lt;tf.Tensor: shape=(13,), dtype=string, numpy=
array([b'[START]', b'this', b'is', b'the', b'first', b'book', b'that',
       b'i', b'did', b'i', b'did', b'.', b'[END]'], dtype=object)&gt;</code></pre>
</div>
</div>

<img data-src="Nb_2c_Traduccion_usando_transformers_keras_files/figure-revealjs/cell-69-output-1.png" class="r-stretch"></section>
<section id="exportar-el-modelo" class="slide level2">
<h2>Exportar el modelo</h2>
<p>Hemos probado el modelo y la inferencia funciona. A continuación, puedes exportarlo como un <code>tf.saved_model</code>. Para aprender cómo guardar y cargar un modelo en formato SavedModel, consulta <a href="https://www.tensorflow.org/guide/saved_model">esta guía</a>.</p>
<p>Crea una clase llamada <code>ExportTranslator</code> extendiendo la subclase <code>tf.Module</code> con un <code>@tf.function</code> en el método <code>__call__</code>:</p>
<p>Dado que el modelo está decodificando las predicciones utilizando <code>tf.argmax</code>, las predicciones son deterministas. El modelo original y uno recargado desde su <code>SavedModel</code> deberían dar predicciones idénticas:</p>
<div id="cell-204" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="32588aad-fd46-4ea7-9939-53f49ca4515d" data-execution_count="71">
<div class="cell-output cell-output-display" data-execution_count="71">
<pre><code>b'this is the first book that i did i did .'</code></pre>
</div>
</div>
<div id="cell-207" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;colab&quot;,&quot;value&quot;:{&quot;base_uri&quot;:&quot;https://localhost:8080/&quot;}}" data-outputid="3e6dbbd3-014b-489d-c341-485bbdff84d8" data-execution_count="74">
<div class="cell-output cell-output-display" data-execution_count="74">
<pre><code>b'this is the first book that i did i did .'</code></pre>
</div>
</div>
</section>
<section id="conclusión" class="slide level2">
<h2>Conclusión</h2>
<p>En este tutorial aprendiste sobre:</p>
<ul>
<li>Los Transformers y su importancia en el aprendizaje automático</li>
<li>Atención, auto-atención y atención multi-cabeza</li>
<li>Codificación posicional con embeddings</li>
<li>La arquitectura codificador-decodificador del Transformer original</li>
<li>Enmascaramiento en la auto-atención</li>
<li>Cómo juntar todo para traducir texto</li>
</ul>
<p>Las desventajas de esta arquitectura son:</p>
<ul>
<li>Para una serie temporal, la salida para un paso de tiempo se calcula a partir de la <em>historia completa</em> en lugar de solo las entradas y el estado oculto actual. Esto <em>podría</em> ser menos eficiente.</li>
<li>Si la entrada tiene una relación temporal/espacial, como texto o imágenes, debe añadirse alguna codificación posicional o el modelo efectivamente verá una bolsa de palabras.</li>
</ul>
<p><em>Este notebook se basó en el notebook de <a href="https://colab.research.google.com/github/tensorflow/text/blob/master/docs/tutorials/transformer.ipynb">Neural Machine Translation with a Transformer and Keras</a> para el curso de Deep Learning práctico en 3 semanas.</em></p>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="../../assets/logos/montevideo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p>Deep Learning · Universidad de Montevideo · Jefferson Rodríguez</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions"><ul><li><a href="https://github.com/jeffersonrodriguezc/deep-learning-en-3-semanas/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>