project:
  type: website

website:
  title: "Deep Learning Practico en 3 Semanas"
  repo-url: https://github.com/jeffersonrodriguezc/deep-learning-en-3-semanas/ 
  repo-actions: [issue]
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: semana_1/index.qmd
        text: Semana 1
      - href: semana_2/index.qmd
        text: Semana 2
      - href: semana_3/index.qmd 
        text: Semana 3
    right: 
      - icon: github
        href: https://github.com/jeffersonrodriguezc/deep-learning-en-3-semanas/
        aria-label: GitHub

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true



